services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d myapp_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true    # ファイル変更をポーリングで監視
      - WATCHPACK_POLLING=true      # Webpack/Turbopackのポーリング有効
      # ⚡ Next.js 15最適化
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - TURBOPACK=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
    depends_on:
      db:
        condition: service_healthy  # DBの起動完了を待つ
    command: bash -c "npm install && npm run dev -- --hostname 0.0.0.0" # docker compose upで実行される
volumes:
  postgresql_data: